//! Protocol Buffers definitions for LAK
//!
//! Generated by tonic-build from `proto/lak.proto`.
//! Re-exports the generated types and service stubs.

// Include the generated code from tonic-build.
// Clippy lints are suppressed: this is machine-generated code.
#[allow(clippy::all, clippy::pedantic)]
pub mod lak {
    tonic::include_proto!("lak");
}

// Re-export common types at crate level
pub use lak::*;
